"""WorkerStrategy — FA-T008 for OpenCode/Hermes/native workers."""

from __future__ import annotations

from typing import Any, Dict, List

from worker.core.propose_orchestrator import ProposeContext, ProposeStrategy

from worker.core.propose import (
    ProposeStrategyResult,
    ExecutableProposal,
)

from agent.services.worker_runtime_selection_service import (
    WorkerRuntimeSelectionService,
    WorkerRuntimeSelectionRequest,
)

from worker.core.runtime_target import (
    WorkerSelectionPolicy,
    WorkerSelectionMode,
    # SelectionDecisionStatus,  # adjust if needed
)

from worker.core.runtime_target import (
    SelectionDecisionStatus,
    WorkerKind,
)


class WorkerStrategy(ProposeStrategy):
    """Strategy that delegates propose to selected worker."""

    def run(self, context: ProposeContext) -> ProposeStrategyResult:
        try:
            # Resolve policy for worker selection (TODO: from ProposePolicy or task-specific)
            policy = WorkerSelectionPolicy(
                mode=WorkerSelectionMode.automatic,
                required_capabilities=["llm_reasoning", "propose"],
            )

            # TODO: Resolve real candidates from worker registry/config
            workers: List[Any] = []  # get_available_workers()
            runtime_targets: List[Any] = []  # get_runtime_targets()

            request = WorkerRuntimeSelectionRequest(
                policy=policy,
                workers=workers,
                runtime_targets=runtime_targets,
                required_capabilities=["propose"],
                execution_mode="propose",
                policy_decision_ref=context.task_id,
                context_boundary_decision="local_preferred",
            )

            service = WorkerRuntimeSelectionService()
            decision = service.select(request)

            if decision.status != SelectionDecisionStatus.selected:
                return ProposeStrategyResult.declined(
                    "worker_strategy",
                    reason=str(decision.reason) if hasattr(decision, "reason") else "no_worker_selected",
                    reason_codes=getattr(decision, "reason_codes", []),
                )

            # TODO: Real delegation to selected worker/runtime
            # worker_adapter = resolve_worker_adapter(decision.selected_worker)
            # output = worker_adapter.propose(context, decision)
            # normalized = self._normalize_output(output)

            # Mock output based on worker kind for testing
            worker_kind_str = getattr(decision.selected_worker, "worker_kind", "unknown").value.lower()
            if worker_kind_str == "hermes":
                output = "Hermes worker generated advisory proposal text."
            elif worker_kind_str == "opencode":
                output = {
                    "tool_calls": [
                        {
                            "name": "write_file",
                            "args": {
                                "path": "mock_opencode_README.md",
                                "content": "# OpenCode Proposal\\nGenerated by worker."
                            }
                        }
                    ]
                }
            else:
                output = {"command": "echo 'Native worker propose complete.'"}

            # Simple worker-specific normalization (LLMResponseNormalizer in FA-T010)
            if isinstance(output, str):
                return ProposeStrategyResult.advisory(
                    "worker_strategy",
                    advisory_text=output,
                )
            # Assume structured dict
            try:
                proposal = ExecutableProposal(
                    proposal_id=f"ws-{context.task_id}",
                    goal_id=context.goal_id,
                    task_id=context.task_id,
                    strategy_id="worker_strategy",
                    command=output.get("command"),
                    tool_calls=output.get("tool_calls", []),
                    expected_artifacts=["proposal_artifacts", "workspace_delta"],
                    safety_flags={},  # From policy
                    metadata={
                        "selected_worker": getattr(decision.selected_worker, "worker_id", "unknown"),
                        "worker_kind": worker_kind_str,
                    },
                )
                return ProposeStrategyResult.executable("worker_strategy", proposal)
            except ValueError as ve:
                return ProposeStrategyResult.failed(
                    "worker_strategy",
                    f"normalization_failed: {ve}"
                )
        except Exception as e:
            return ProposeStrategyResult.failed(
                "worker_strategy",
                f"worker_strategy_error: {str(e)}"
            )
