from __future__ import annotations

from agent.services.editor_tui_surface_state import (
    CAPABILITY_SURFACE_MODEL,
    COMMON_OBJECT_MODEL,
    ERROR_DEGRADED_STATE_MODEL,
    FRONTEND_CONTRACT_INVENTORY,
    NVIM_ARCHITECTURE_DECISION,
    NVIM_COMMAND_SURFACE,
    NVIM_EDITOR_MATRIX,
    ONBOARDING_SPLIT_MODEL,
    RELEASE_SMOKE_STRATEGY,
    SHARED_UI_BOUNDARY_MODEL,
    TRACE_AUDIT_LINKING_RULES,
    TUI_FRAMEWORK_ARCHITECTURE_DECISION,
    TUI_GLOBAL_NAV_LAYOUT,
    TUI_INFORMATION_ARCHITECTURE,
    build_connection_profile_abstraction,
    build_nvim_analyze_flow,
    build_nvim_approval_awareness_view,
    build_nvim_artifact_preview,
    build_nvim_blueprint_project_start_commands,
    build_nvim_connection_auth_support,
    build_nvim_context_inspection_panel,
    build_nvim_diff_proposal_render,
    build_nvim_external_shortcuts,
    build_nvim_first_run_guided_setup,
    build_nvim_goal_submission_flow,
    build_nvim_knowledge_context_source_summary,
    build_nvim_navigation_links,
    build_nvim_patch_planning_flow,
    build_nvim_quick_action_palette,
    build_nvim_review_flow,
    build_nvim_task_context_view,
    build_nvim_trace_diagnostic_summary,
    build_tui_approval_action_flow,
    build_tui_approval_queue_view,
    build_tui_artifact_view,
    build_tui_audit_summary_view,
    build_tui_audit_trace_drilldown,
    build_tui_auth_session_support,
    build_tui_cross_view_search_filtering,
    build_tui_empty_error_state_ux,
    build_tui_goal_submission_entry,
    build_tui_goal_view,
    build_tui_health_runtime_diagnostics_view,
    build_tui_keyboard_navigation_refinement,
    build_tui_kritis_dashboard_summary,
    build_tui_log_stream_view,
    build_tui_policy_denial_view,
    build_tui_provider_backend_visibility_view,
    build_tui_repair_approval_execution_review,
    build_tui_repair_session_views,
    build_tui_runtime_status_header,
    build_tui_state_persistence_resume,
    build_tui_task_board_view,
    build_tui_task_detail_view,
    build_tui_task_filtering_grouping,
    collect_nvim_editor_context,
)

from typing import Any


def build_editor_tui_foundation_snapshot(
    *,
    connection_profiles: list[dict[str, Any]],
    active_profile_id: str | None,
    nvim_editor_state: dict[str, Any],
    nvim_goal_text: str,
    nvim_tasks: list[dict[str, Any]] | None = None,
    nvim_artifact: dict[str, Any] | None = None,
    nvim_diff_proposals: list[dict[str, Any]] | None = None,
    nvim_source_locations: list[dict[str, Any]] | None = None,
    nvim_traces: list[dict[str, Any]] | None = None,
    nvim_knowledge_sources: list[dict[str, Any]] | None = None,
    tui_tasks: list[dict[str, Any]] | None = None,
    tui_artifacts: list[dict[str, Any]] | None = None,
    tui_goals: list[dict[str, Any]] | None = None,
    tui_logs: list[dict[str, Any]] | None = None,
    tui_approvals: list[dict[str, Any]] | None = None,
    tui_audit_chains: list[dict[str, Any]] | None = None,
    tui_policy_denials: list[dict[str, Any]] | None = None,
    tui_repair_sessions: list[dict[str, Any]] | None = None,
    tui_diagnostics: list[dict[str, Any]] | None = None,
    tui_providers: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    profile_model = build_connection_profile_abstraction(
        connection_profiles,
        active_profile_id=active_profile_id,
    )
    active_profile = next(
        (profile for profile in profile_model["profiles"] if profile["id"] == profile_model["active_profile_id"]),
        profile_model["profiles"][0],
    )
    nvim_context = collect_nvim_editor_context(nvim_editor_state)
    nvim_goal_submission = build_nvim_goal_submission_flow(
        goal_text=nvim_goal_text,
        editor_context=nvim_context,
        include_selection=True,
    )
    nvim_task_view = build_nvim_task_context_view(
        nvim_tasks or [],
        current_project=nvim_context.get("project_root"),
    )
    nvim_artifact_preview = build_nvim_artifact_preview(
        nvim_artifact or {"id": "artifact-preview", "type": "text", "content": ""},
    )
    nvim_navigation = build_nvim_navigation_links(
        task_item=(nvim_tasks or [{"id": "task-0", "title": "No task yet", "status": "todo", "priority": "P1"}])[0],
        artifact_items=[nvim_artifact or {"id": "artifact-preview", "title": "Preview", "type": "text"}],
        source_locations=nvim_source_locations or [],
    )
    tui_task_board = build_tui_task_board_view(tui_tasks or [])
    tui_approval_queue = build_tui_approval_queue_view(tui_approvals or [])
    first_approval = (tui_approvals or [{"id": "approval-0", "scope": "none", "state": "pending"}])[0]
    first_trace = (nvim_traces or [{"trace_id": "trace-0", "route": "none", "status": "unknown"}])[0]
    return {
        "schema": "editor_tui_foundation_snapshot_v1",
        "shared_ui_boundary_model": dict(SHARED_UI_BOUNDARY_MODEL),
        "frontend_contract_inventory": dict(FRONTEND_CONTRACT_INVENTORY),
        "common_object_model": dict(COMMON_OBJECT_MODEL),
        "connection_profile_abstraction": profile_model,
        "capability_surface_model": dict(CAPABILITY_SURFACE_MODEL),
        "error_degraded_state_model": dict(ERROR_DEGRADED_STATE_MODEL),
        "trace_audit_linking_rules": dict(TRACE_AUDIT_LINKING_RULES),
        "onboarding_split_model": dict(ONBOARDING_SPLIT_MODEL),
        "release_smoke_strategy": dict(RELEASE_SMOKE_STRATEGY),
        "nvim_plugin_architecture": dict(NVIM_ARCHITECTURE_DECISION),
        "nvim_editor_matrix": dict(NVIM_EDITOR_MATRIX),
        "nvim_connection_auth_support": build_nvim_connection_auth_support(active_profile),
        "nvim_command_surface": dict(NVIM_COMMAND_SURFACE),
        "nvim_quick_action_palette": build_nvim_quick_action_palette(),
        "nvim_editor_context": nvim_context,
        "nvim_goal_submission_flow": nvim_goal_submission,
        "nvim_analyze_flow": build_nvim_analyze_flow(editor_context=nvim_context),
        "nvim_review_flow": build_nvim_review_flow(editor_context=nvim_context),
        "nvim_patch_planning_flow": build_nvim_patch_planning_flow(editor_context=nvim_context),
        "nvim_task_context_view": nvim_task_view,
        "nvim_artifact_preview": nvim_artifact_preview,
        "nvim_context_inspection_panel": build_nvim_context_inspection_panel(nvim_context),
        "nvim_diff_proposal_render": build_nvim_diff_proposal_render(proposals=nvim_diff_proposals or []),
        "nvim_navigation_links": nvim_navigation,
        "nvim_external_shortcuts": build_nvim_external_shortcuts(
            base_url=active_profile["endpoint"],
            task_id=nvim_navigation["task"]["id"],
            artifact_id=nvim_artifact_preview["artifact_id"],
        ),
        "nvim_blueprint_project_start_commands": build_nvim_blueprint_project_start_commands(),
        "nvim_approval_awareness_view": build_nvim_approval_awareness_view(
            operation_id="op-risk-1",
            approval_state="review_required",
            policy_reason="sensitive_write_operation",
        ),
        "nvim_trace_diagnostic_summary": build_nvim_trace_diagnostic_summary(nvim_traces or []),
        "nvim_knowledge_context_source_summary": build_nvim_knowledge_context_source_summary(
            nvim_knowledge_sources or []
        ),
        "nvim_first_run_guided_setup": build_nvim_first_run_guided_setup(),
        "tui_framework_architecture": dict(TUI_FRAMEWORK_ARCHITECTURE_DECISION),
        "tui_information_architecture": dict(TUI_INFORMATION_ARCHITECTURE),
        "tui_auth_session_support": build_tui_auth_session_support(active_profile),
        "tui_global_navigation_layout": dict(TUI_GLOBAL_NAV_LAYOUT),
        "tui_runtime_status_header": build_tui_runtime_status_header(active_profile),
        "tui_task_board_view": tui_task_board,
        "tui_task_detail_view": build_tui_task_detail_view(
            (tui_tasks or [{"id": "task-0", "title": "No task yet", "status": "todo", "priority": "P1"}])[0],
            artifacts=tui_artifacts or [],
            routing_hints=["hub_worker_orchestration_path"],
        ),
        "tui_artifact_view": build_tui_artifact_view(tui_artifacts or []),
        "tui_goal_view": build_tui_goal_view(tui_goals or []),
        "tui_goal_submission_entry": build_tui_goal_submission_entry(),
        "tui_task_filtering_grouping": build_tui_task_filtering_grouping(task_board=tui_task_board),
        "tui_log_stream_view": build_tui_log_stream_view(tui_logs or []),
        "tui_approval_queue_view": tui_approval_queue,
        "tui_approval_action_flow": build_tui_approval_action_flow(
            first_approval,
            action="approve",
            operator_note="approved after context review",
        ),
        "tui_audit_summary_view": build_tui_audit_summary_view(tui_audit_chains or []),
        "tui_audit_trace_drilldown": build_tui_audit_trace_drilldown(
            trace_id=first_trace["trace_id"],
            events=(tui_audit_chains or [{"event_id": "event-0", "message": "no audit event"}]),
            redaction_applied=True,
        ),
        "tui_policy_denial_view": build_tui_policy_denial_view(tui_policy_denials or []),
        "tui_kritis_dashboard_summary": build_tui_kritis_dashboard_summary(
            audit_health="healthy",
            approval_backlog=len(tui_approval_queue["queue"]),
            mutation_status="guarded",
            policy_posture="strict",
        ),
        "tui_repair_session_views": build_tui_repair_session_views(tui_repair_sessions or []),
        "tui_repair_approval_execution_review": build_tui_repair_approval_execution_review(
            repair_session_id=(tui_repair_sessions or [{"session_id": "repair-0"}])[0]["session_id"],
            dry_run_supported=True,
            approval_required=True,
        ),
        "tui_health_runtime_diagnostics_view": build_tui_health_runtime_diagnostics_view(
            health="ok",
            readiness="ready",
            diagnostics=tui_diagnostics or [],
        ),
        "tui_provider_backend_visibility_view": build_tui_provider_backend_visibility_view(tui_providers or []),
        "tui_keyboard_navigation_refinement": build_tui_keyboard_navigation_refinement(),
        "tui_cross_view_search_filtering": build_tui_cross_view_search_filtering(),
        "tui_state_persistence_resume": build_tui_state_persistence_resume(
            selected_profile_id=active_profile["id"],
            last_view="tasks",
        ),
        "tui_empty_error_state_ux": build_tui_empty_error_state_ux(),
    }
