from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from agent.db_models import (
    MlInternDatasetDB,
    MlInternTrainingAttemptDB,
    MlInternTrainingEventDB,
    MlInternTrainingJobDB,
)


@dataclass(frozen=True)
class MlInternTrainingPrincipal:
    tenant_id: str
    subject: str

    def __post_init__(self) -> None:
        if not self.tenant_id.strip() or not self.subject.strip():
            raise ValueError("training principal requires tenant_id and subject")


class MlInternTrainingRepositoryPort(Protocol):
    def create_dataset(self, dataset: MlInternDatasetDB) -> tuple[MlInternDatasetDB, bool]: ...
    def get_dataset(self, principal: MlInternTrainingPrincipal, dataset_id: str) -> MlInternDatasetDB | None: ...
    def list_datasets(
        self, principal: MlInternTrainingPrincipal, *, limit: int, offset: int
    ) -> list[MlInternDatasetDB]: ...
    def save_dataset(self, dataset: MlInternDatasetDB, *, expected_version: int) -> MlInternDatasetDB: ...
    def create_job(self, job: MlInternTrainingJobDB) -> tuple[MlInternTrainingJobDB, bool]: ...
    def create_job_with_capacity(
        self, job: MlInternTrainingJobDB, *, outstanding_limit: int
    ) -> tuple[MlInternTrainingJobDB, bool]: ...
    def get_job(self, principal: MlInternTrainingPrincipal, job_id: str) -> MlInternTrainingJobDB | None: ...
    def get_job_by_idempotency(
        self, principal: MlInternTrainingPrincipal, idempotency_key_digest: str
    ) -> MlInternTrainingJobDB | None: ...
    def count_active_jobs(self) -> int: ...
    def count_executing_jobs(self) -> int: ...
    def count_queued_jobs(self) -> int: ...
    def list_active_jobs(self, *, limit: int = 1000) -> list[MlInternTrainingJobDB]: ...
    def list_queued_jobs(self, *, limit: int = 10_000) -> list[MlInternTrainingJobDB]: ...
    def list_jobs(
        self,
        principal: MlInternTrainingPrincipal,
        *,
        limit: int,
        offset: int,
        status: str | None = None,
        backend: str | None = None,
        dataset_id: str | None = None,
    ) -> list[MlInternTrainingJobDB]: ...
    def count_jobs(
        self,
        principal: MlInternTrainingPrincipal,
        *,
        status: str | None = None,
        backend: str | None = None,
        dataset_id: str | None = None,
    ) -> int: ...
    def save_job(self, job: MlInternTrainingJobDB, *, expected_version: int) -> MlInternTrainingJobDB: ...
    def try_acquire_execution_slot(
        self, job_id: str, *, limit: int, lease_expires_at: float, now: float | None = None
    ) -> int | None: ...
    def renew_execution_slot(self, job_id: str, *, lease_expires_at: float) -> bool: ...
    def release_execution_slot(self, job_id: str) -> None: ...
    def append_event(
        self, principal: MlInternTrainingPrincipal, job_id: str, *, event_type: str, dedupe_key: str, payload: dict
    ) -> MlInternTrainingEventDB: ...
    def list_events(
        self, principal: MlInternTrainingPrincipal, job_id: str, *, after_sequence: int, limit: int
    ) -> list[MlInternTrainingEventDB]: ...
    def create_attempt(self, attempt: MlInternTrainingAttemptDB) -> MlInternTrainingAttemptDB: ...
    def get_attempt(self, attempt_id: str) -> MlInternTrainingAttemptDB | None: ...
    def list_attempts(self, job_id: str, *, limit: int = 100) -> list[MlInternTrainingAttemptDB]: ...
    def next_attempt_number(self, job_id: str) -> int: ...
    def save_attempt(
        self, attempt: MlInternTrainingAttemptDB, *, expected_version: int
    ) -> MlInternTrainingAttemptDB: ...
