"""Narrow authority, catalog and persistence seams for retention."""

from typing import Protocol


class RetentionPolicyPort(Protocol):
    def require_revoke(self, principal, project, artifact_id): ...


class RetiredAssetPort(Protocol):
    def get_retired(self, tenant, project, artifact_id): ...


class RetentionGrantStorePort(Protocol):
    def get(self, key): ...
    def install(self, record, *, expected_revision): ...
    def cancel(self, key, *, expected_revision, actor): ...


class RetentionClaimStorePort(Protocol):
    def due(self, now_ms, *, limit): ...
    def claim(self, observed, now_ms): ...
    def require_claim(self, record, now_ms): ...
    def finish(self, record, state, now_ms) -> bool: ...


class RetentionErasurePort(Protocol):
    def purge(self, principal, project, artifact_id, *, expected_revision, require_current): ...
