version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
    labels:
      - dependencies
      - backend
    commit-message:
      prefix: "deps(python)"

  - package-ecosystem: "npm"
    directory: "/frontend-angular"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: "deps(frontend)"
