"""Reviewable source boundaries fingerprinted by the semantic-media Playwright gates."""

from __future__ import annotations


# The pair report is reused as release evidence for the live speech and peer
# evidence paths.  Keep its source boundary explicit and reviewable: these are
# the production layers executed by the Playwright scenario plus the UI/facade
# consumers of its shared acceptance policy, not a recursive repository glob.
# A change to any listed contract, adapter or persistence guard therefore
# invalidates older evidence.
_PAIR_ANGULAR_SOURCE_PATHS = (
    "frontend-angular/angular.json",
    "frontend-angular/package.json",
    "frontend-angular/playwright.config.ts",
    "frontend-angular/tsconfig.semantic-media-e2e.json",
    "frontend-angular/src/bootstrap-ananta-application.ts",
    "frontend-angular/src/main.ts",
    "frontend-angular/src/main.semantic-media-e2e.ts",
    "frontend-angular/src/app/e2e/semantic-media-pair-live-driver.ts",
    "frontend-angular/src/app/e2e/semantic-media-pair-ui-observer.ts",
    "frontend-angular/src/app/features/voice/peer-evidence-acceptance.ts",
    "frontend-angular/src/app/features/voice/peer-evidence-sync-panel.component.ts",
    "frontend-angular/src/app/features/voice/peer-evidence-sync.facade.ts",
    "frontend-angular/src/app/features/voice/semantic-media-program-host.component.ts",
    "frontend-angular/src/app/features/voice/semantic-media-program.facade.ts",
    "frontend-angular/src/app/features/voice/semantic-speech-panel.component.ts",
    "frontend-angular/src/app/features/voice/voice-audio-capture.ts",
    "frontend-angular/src/app/services/speech-transcript-revision.store.ts",
    "frontend-angular/src/app/features/voice/voice-api.service.ts",
    "frontend-angular/src/app/features/voice/voice.models.ts",
    "frontend-angular/src/app/features/voice/voice-live-session.controller.ts",
    "frontend-angular/src/app/features/voice/voice-long-run.controller.ts",
    "frontend-angular/src/app/services/auth.interceptor.ts",
    "frontend-angular/src/app/services/hub-api-core.service.ts",
    "frontend-angular/src/app/services/semantic-speech-capture-producer.service.ts",
    "frontend-angular/src/app/services/semantic-speech-runtime-coordinator.service.ts",
    "frontend-angular/src/app/services/semantic-speech-settings.ts",
    "frontend-angular/src/app/services/semantic-speech-source-correction-api.service.ts",
    "frontend-angular/src/app/services/semantic-speech-transport.service.ts",
    "frontend-angular/src/app/services/semantic-speech-quality-controller.service.ts",
    "frontend-angular/src/app/shared/crypto/sha256.ts",
    "frontend-angular/src/app/services/speech-evidence-hub-curation.facade.ts",
    "frontend-angular/src/app/services/speech-evidence-sync-api.service.ts",
    "frontend-angular/src/app/services/speech-evidence-sync.validators.ts",
    "frontend-angular/src/app/services/webrtc-datachannel.service.ts",
    "frontend-angular/src/app/services/network-profile.service.ts",
    "frontend-angular/src/app/services/webrtc-priority-send-queue.ts",
    "frontend-angular/src/app/services/webrtc-send-operation.ts",
    "frontend-angular/src/app/services/webrtc-session.service.ts",
    "frontend-angular/src/app/services/webrtc-signaling.service.ts",
    "frontend-angular/src/app/services/webrtc-transport.service.ts",
    "frontend-angular/tests/global-setup.ts",
    "frontend-angular/tests/global-teardown.ts",
)


_PAIR_HUB_SOURCE_PATHS = (
    "agent/bootstrap/routes.py",
    "agent/bootstrap/semantic_media_services.py",
    "agent/db_models/__init__.py",
    "agent/db_models/governance.py",
    "agent/db_models/semantic_media.py",
    "agent/db_models/speech_evidence.py",
    "agent/db_models/speech_evidence_sync.py",
    "agent/repositories/semantic_media_audit_outbox.py",
    "agent/models/semantic_media_audit.py",
    "agent/models/semantic_media_content_policy.py",
    "agent/repositories/semantic_media_audit_repository.py",
    "agent/repositories/semantic_relay_repository.py",
    "agent/models/semantic_relay_errors.py",
    "agent/models/semantic_relay_limits.py",
    "agent/repositories/semantic_relay_shared_store.py",
    "agent/repositories/speech_consent_repository.py",
    "agent/repositories/speech_evidence.py",
    "agent/repositories/speech_evidence_lineage.py",
    "agent/repositories/speech_evidence_sync.py",
    "agent/repositories/speech_evidence_offer_rows.py",
    "agent/repositories/speech_evidence_peer_keys.py",
    "agent/repositories/speech_evidence_replay_window.py",
    "agent/repositories/speech_evidence_sync_records.py",
    "agent/repositories/speech_evidence_transfers.py",
    "agent/models/speech_evidence_offer.py",
    "agent/repositories/webrtc_epoch_repository.py",
    "agent/repositories/webrtc_peer_key_repository.py",
    "agent/models/webrtc_peer_key_confirmation.py",
    "agent/routes/semantic_media_e2e_support.py",
    "agent/services/webrtc_peer_key_confirmation_service.py",
    "agent/routes/speech_evidence_sync.py",
    "agent/routes/voice.py",
    "agent/routes/route_dependency_seam.py",
    "agent/routes/voice_request_policy.py",
    "agent/routes/voice_route_dependencies.py",
    "agent/routes/voice_blueprint.py",
    "agent/routes/voice_command_routes.py",
    "agent/routes/voice_hub_execution.py",
    "agent/routes/voice_recognition_context.py",
    "agent/routes/voice_request_deadlines.py",
    "agent/routes/voice_request_support.py",
    "agent/routes/voice_source_correction_routes.py",
    "agent/routes/voice_stream_create_routes.py",
    "agent/routes/voice_stream_lifecycle_routes.py",
    "agent/routes/voice_transcription_routes.py",
    "agent/routes/voice_http_adapter.py",
    "agent/routes/voice_live_runs.py",
    "agent/services/ml_intern_speech_admission_policy.py",
    "agent/services/ml_intern_speech_dataset_build_service.py",
    "agent/services/ml_intern_speech_dataset_port.py",
    "agent/services/semantic_media_audit_service.py",
    "agent/ports/semantic_media_audit.py",
    "agent/services/semantic_media_feature_flags.py",
    "agent/services/semantic_relay_authorization.py",
    "agent/services/semantic_relay_composition.py",
    "agent/services/semantic_relay_limits.py",
    "agent/services/semantic_relay_observability.py",
    "agent/services/semantic_relay_rate_limiter.py",
    "agent/services/semantic_relay_service.py",
    "agent/services/semantic_speech_relay.py",
    "agent/services/share_session_relay_membership.py",
    "agent/services/share_session_service.py",
    "agent/services/speech_evidence_admission_policy.py",
    "agent/services/speech_evidence_consent_service.py",
    "agent/services/speech_evidence_curation_task_service.py",
    "agent/services/speech_evidence_encryption_port.py",
    "agent/services/speech_evidence_key_service.py",
    "agent/services/speech_evidence_offer_service.py",
    "agent/services/speech_evidence_peer_curation_composition.py",
    "agent/services/speech_peer_curation_adapters.py",
    "agent/services/speech_peer_curation_dataset.py",
    "agent/services/speech_peer_curation_group_decoder.py",
    "agent/services/speech_peer_curation_revocation.py",
    "agent/services/speech_peer_curation_values.py",
    "agent/services/speech_evidence_poisoning_policy.py",
    "agent/services/speech_evidence_receipt_service.py",
    "agent/services/speech_evidence_store_service.py",
    "agent/services/speech_evidence_sync_composition.py",
    "agent/services/speech_evidence_sync_consent_adapter.py",
    "agent/services/speech_evidence_sync_ports.py",
    "agent/services/speech_evidence_sync_share_session_adapters.py",
    "agent/services/voice_governance_domain.py",
    "agent/models/voice_governance_domain.py",
    "agent/services/voice_delegation_task_service.py",
    "agent/services/voice_idempotency_service.py",
    "agent/services/voice_live_run_correction_service.py",
    "agent/services/voice_live_run_service.py",
    "agent/services/voice_live_run_compensator.py",
    "agent/services/voice_live_run_contracts.py",
    "agent/services/voice_live_run_fences.py",
    "agent/services/voice_live_run_finalizer.py",
    "agent/services/voice_live_run_input_validator.py",
    "agent/services/voice_live_run_snapshot_builder.py",
    "agent/services/voice_live_run_timeline.py",
    "agent/services/voice_live_run_start_lease_service.py",
    "agent/services/voice_live_run_task_port.py",
    "agent/services/voice_provider.py",
    "agent/services/voice_stream_session_service.py",
    "agent/services/webrtc_epoch_service.py",
    "agent/services/webrtc_peer_identity_service.py",
    "voice_runtime/evidence_identity.py",
    "voice_runtime/evidence_quality.py",
    "voice_runtime/app.py",
    "voice_runtime/backends/provenance.py",
    "voice_runtime/backends/registry.py",
    "voice_runtime/backends/router.py",
    "voice_runtime/backends/whisper_cpp.py",
    "voice_runtime/config.py",
    "voice_runtime/execution_control.py",
    "voice_runtime/execution_policy.py",
    "voice_runtime/model_manifest.py",
    "voice_runtime/parallel.py",
    "voice_runtime/pipeline.py",
    "voice_runtime/pipeline_adaptive_rerun.py",
    "voice_runtime/pipeline_confidence_rerun.py",
    "voice_runtime/pipeline_diarization.py",
    "voice_runtime/pipeline_execution.py",
    "voice_runtime/pipeline_postprocessing.py",
    "voice_runtime/pipeline_results.py",
    "voice_runtime/preprocessing/audio_decode.py",
    "voice_runtime/resources.py",
    "voice_runtime/routes.py",
    "voice_runtime/streaming.py",
    "voice_runtime/streaming_protocol.py",
    "voice_runtime/streaming_recognizer_factories.py",
    "voice_runtime/streaming_recognizers.py",
    "voice_runtime/streaming_session.py",
    "voice_runtime/streaming_transcript.py",
)


_PAIR_CONTRACT_AND_SCHEMA_SOURCE_PATHS = (
    "ananta_contracts/speech_evidence_crypto.py",
    "ananta_contracts/speech_evidence_governance.py",
    "ananta_contracts/speech_evidence_sync.py",
    "ananta_contracts/speech_evidence_sync_payloads.py",
    "ananta_contracts/speech_evidence_sync_primitives.py",
    "ananta_contracts/webrtc_datachannel.py",
    "migrations/versions/a9b0c1d2e3f4_add_signed_speech_evidence_offer_previews.py",
    "migrations/versions/d5e6f7a8b9c0_add_speech_evidence_sync_control_plane.py",
    "migrations/versions/d8e9f0a1b2c3_add_semantic_relay_store.py",
    "migrations/versions/e9f0a1b2c3d4_add_semantic_relay_wire_metadata.py",
    "migrations/versions/f0a1b2c3d4e5_add_speech_evidence_governance.py",
    "scripts/e2e/semantic_media_pair_e2e.py",
)


def _source_paths(spec: str, common: tuple[str, ...]) -> tuple[str, ...]:
    additions: tuple[str, ...] = ()
    if spec == "semantic-media-pair.spec.ts":
        additions = (
            *_PAIR_ANGULAR_SOURCE_PATHS,
            *_PAIR_HUB_SOURCE_PATHS,
            *_PAIR_CONTRACT_AND_SCHEMA_SOURCE_PATHS,
        )
    elif spec == "semantic-media-group.spec.ts":
        additions = (
            "frontend-angular/angular.json",
            "frontend-angular/package.json",
            "frontend-angular/playwright.config.ts",
            "frontend-angular/tsconfig.semantic-media-e2e.json",
            "frontend-angular/src/bootstrap-ananta-application.ts",
            "frontend-angular/src/main.ts",
            "frontend-angular/src/main.semantic-media-e2e.ts",
            "frontend-angular/src/app/e2e/semantic-media-group-live-driver.ts",
            "frontend-angular/src/app/services/e2e-encryption.service.ts",
            "frontend-angular/src/app/services/livekit-sfu-room.adapter.ts",
            "frontend-angular/src/app/services/livekit-sfu-transport.service.ts",
            "frontend-angular/src/app/services/secure-key-store.service.ts",
            "frontend-angular/src/app/services/semantic-sfu-admission-api.service.ts",
            "frontend-angular/src/app/services/semantic-sfu-group-key-api.service.ts",
            "frontend-angular/src/app/services/semantic-sfu-group-key.service.ts",
            "frontend-angular/src/app/services/semantic-sfu-path-coordinator.service.ts",
            "frontend-angular/src/app/services/webrtc-group-key.service.ts",
            "frontend-angular/src/app/services/webrtc-peer-key.service.ts",
            "agent/bootstrap/routes.py",
            "agent/bootstrap/semantic_media_services.py",
            "agent/db_models/semantic_media.py",
            "agent/repositories/semantic_sfu_admission_repository.py",
            "agent/repositories/webrtc_epoch_repository.py",
            "agent/repositories/webrtc_peer_key_repository.py",
            "agent/routes/semantic_media_e2e_support.py",
            "agent/routes/semantic_sfu_admission.py",
            "agent/routes/share_sessions.py",
            "agent/routes/share_session_chat_routes.py",
            "agent/routes/share_session_key_routes.py",
            "agent/routes/share_session_relay_routes.py",
            "agent/routes/share_session_route_support.py",
            "agent/routes/share_session_view_routes.py",
            "agent/services/semantic_sfu_admission_service.py",
            "agent/services/semantic_sfu_group_key_service.py",
            "agent/services/share_security_negotiation_service.py",
            "agent/services/share_session_service.py",
            "agent/services/webrtc_epoch_service.py",
            "agent/services/webrtc_group_key_authorization_service.py",
            "agent/services/webrtc_peer_identity_service.py",
            "migrations/versions/e6f7a8b9c0d1_add_semantic_sfu_admission_state.py",
        )
    elif spec == "semantic-media-accessibility.spec.ts":
        additions = (
            "frontend-angular/src/app/app.component.ts",
            "frontend-angular/src/app/features/voice/semantic-media-program-host.component.ts",
            "frontend-angular/src/app/features/voice/semantic-media-program-shell.component.html",
            "frontend-angular/src/app/features/voice/semantic-media-program-shell.component.ts",
            "frontend-angular/src/app/features/voice/semantic-media-program.facade.ts",
        )
    elif spec == "semantic-visual-lifecycle.spec.ts":
        additions = (
            "frontend-angular/src/main.ts",
            "frontend-angular/src/app/e2e/semantic-visual-lifecycle-live-driver.ts",
            "frontend-angular/src/app/services/semantic-visual-controller.service.ts",
            "frontend-angular/src/app/services/semantic-visual-fallback.service.ts",
            "frontend-angular/src/app/services/semantic-recovery.service.ts",
        )
    return (*common, *additions)
