import unittest
import fibonacci

class TestFibonacciFunctions(unittest.TestCase):

    # Test Recursive Function
    def test_fibonacci_recursive(self):
        # Test base cases
        self.assertEqual(fibonacci.fibonacci_recursive(0), 0)
        self.assertEqual(fibonacci.fibonacci_recursive(1), 1)
        # Test a few known values
        self.assertEqual(fibonacci.fibonacci_recursive(2), 1)
        self.assertEqual(fibonacci.fibonacci_recursive(3), 2)
        self.assertEqual(fibonacci.fibonacci_recursive(6), 8)
        self.assertEqual(fibonacci.fibonacci_recursive(10), 55)

    # Test Iterative Function
    def test_fibonacci_iterative(self):
        # Test base cases
        self.assertEqual(fibonacci.fibonacci_iterative(0), 0)
        self.assertEqual(fibonacci.fibonacci_iterative(1), 1)
        # Test a few known values
        self.assertEqual(fibonacci.fibonacci_iterative(2), 1)
        self.assertEqual(fibonacci.fibonacci_iterative(3), 2)
        self.assertEqual(fibonacci.fibonacci_iterative(6), 8)
        self.assertEqual(fibonacci.fibonacci_iterative(10), 55)
        
    # Test List Generator Function
    def test_generate_fibonacci_list(self):
        # Test generating the first 10 numbers
        expected_list_10 = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
        self.assertEqual(fibonacci.generate_fibonacci_list(10), expected_list_10)
        
        # Test generating the first 1 number
        self.assertEqual(fibonacci.generate_fibonacci_list(1), [0])
        
        # Test generating the first 0 numbers
        self.assertEqual(fibonacci.generate_fibonacci_list(0), [])

# --- Integration Test Example (Simple check for list coherence) ---

class IntegrationTest(unittest.TestCase):
    def test_manual_sequence_validation(self):
        # Check if the last number generated by the list approach follows the pattern
        # Get 5 numbers: [0, 1, 1, 2, 3]
        list_5 = fibonacci.generate_fibonacci_list(5)
        # Calculate the next expected number (which would be the 6th element, index 5)
        expected_next = list_5[-1] + list_5[-2] if len(list_5) >= 2 else 0
        self.assertEqual(list_5[-1], fibonacci.generate_fibonacci_list(6)[-2]) # Basic check of sequence flow
        # A more robust integration would involve passing the list to a new function or simulating usage.
        pass

if __name__ == '__main__':
    unittest.main()
