from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

TUI_SECTION_ORDER = (
    "Dashboard",
    "Goals",
    "Tasks",
    "Artifacts",
    "Knowledge",
    "Config",
    "System",
    "Teams",
    "Instruction",
    "Automation",
    "Audit",
    "Repair",
    "Help",
)

CLASS_TUI_MVP = "tui-mvp"
CLASS_TUI_ADVANCED = "tui-advanced"
CLASS_BROWSER_FALLBACK = "browser-fallback"
CLASS_NOT_TERMINAL = "not-suitable-for-terminal"


@dataclass(frozen=True)
class ApiSurfaceMethod:
    section: str
    method: str
    http_method: str
    endpoint: str
    classification: str
    notes: str


def _entries() -> tuple[ApiSurfaceMethod, ...]:
    return (
        ApiSurfaceMethod(
            "Dashboard",
            "get_dashboard_read_model",
            "GET",
            "/dashboard/read-model",
            CLASS_TUI_MVP,
            "Primary runtime snapshot.",
        ),
        ApiSurfaceMethod(
            "Dashboard",
            "get_assistant_read_model",
            "GET",
            "/assistant/read-model",
            CLASS_TUI_ADVANCED,
            "Optional assistant detail card.",
        ),
        ApiSurfaceMethod("Goals", "list_goals", "GET", "/goals", CLASS_TUI_MVP, "Goal list and summary."),
        ApiSurfaceMethod(
            "Goals", "list_goal_modes", "GET", "/goals/modes", CLASS_TUI_ADVANCED, "Mode-aware goal creation hints."
        ),
        ApiSurfaceMethod(
            "Goals",
            "create_goal",
            "POST",
            "/goals",
            CLASS_TUI_ADVANCED,
            "Explicit goal creation with mode/context payload.",
        ),
        ApiSurfaceMethod(
            "Goals",
            "get_goal_detail",
            "GET",
            "/goals/{id}/detail",
            CLASS_TUI_ADVANCED,
            "Goal detail with trace and related entities.",
        ),
        ApiSurfaceMethod(
            "Goals",
            "get_goal_plan",
            "GET",
            "/goals/{id}/plan",
            CLASS_TUI_ADVANCED,
            "Readable terminal plan tree representation.",
        ),
        ApiSurfaceMethod(
            "Goals",
            "patch_goal_plan_node",
            "PATCH",
            "/goals/{id}/plan/nodes/{node_id}",
            CLASS_BROWSER_FALLBACK,
            "Node patching remains browser-first for safety.",
        ),
        ApiSurfaceMethod(
            "Goals",
            "get_goal_governance_summary",
            "GET",
            "/goals/{id}/governance-summary",
            CLASS_TUI_ADVANCED,
            "Goal governance summary and risk state.",
        ),
        ApiSurfaceMethod("Tasks", "list_tasks", "GET", "/tasks", CLASS_TUI_MVP, "Task board baseline."),
        ApiSurfaceMethod(
            "Tasks",
            "get_task",
            "GET",
            "/tasks/{id}",
            CLASS_TUI_ADVANCED,
            "Task detail with owner/agent/execution state.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "get_task_timeline",
            "GET",
            "/tasks/timeline",
            CLASS_TUI_ADVANCED,
            "Task timeline with status/team/agent filters.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "get_task_logs",
            "GET",
            "/tasks/{id}/logs",
            CLASS_TUI_ADVANCED,
            "Task log view with refresh workflow.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "patch_task",
            "PATCH",
            "/tasks/{id}",
            CLASS_BROWSER_FALLBACK,
            "Task patch action requires explicit confirmation.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "assign_task",
            "POST",
            "/tasks/{id}/assign",
            CLASS_BROWSER_FALLBACK,
            "Task assignment is guarded and confirmation-based.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "propose_task_step",
            "POST",
            "/tasks/{id}/step/propose",
            CLASS_BROWSER_FALLBACK,
            "Proposal action is guarded and auditable.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "execute_task_step",
            "POST",
            "/tasks/{id}/step/execute",
            CLASS_BROWSER_FALLBACK,
            "Execution action is guarded and auditable.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "review_task_proposal",
            "POST",
            "/tasks/{id}/review",
            CLASS_BROWSER_FALLBACK,
            "Approve/reject proposal review is explicit and auditable.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "get_task_orchestration_read_model",
            "GET",
            "/tasks/orchestration/read-model",
            CLASS_TUI_ADVANCED,
            "Orchestration state split by normal/blocked/failed/stale.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "list_archived_tasks",
            "GET",
            "/tasks/archived",
            CLASS_TUI_ADVANCED,
            "Archived task list for restore/cleanup workflow.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "restore_archived_task",
            "POST",
            "/tasks/archived/{id}/restore",
            CLASS_BROWSER_FALLBACK,
            "Restore archived task with explicit confirmation.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "cleanup_archived_tasks",
            "POST",
            "/tasks/archived/cleanup",
            CLASS_BROWSER_FALLBACK,
            "Bulk cleanup requires impact summary and confirmation.",
        ),
        ApiSurfaceMethod(
            "Tasks",
            "delete_archived_task",
            "DELETE",
            "/tasks/archived/{id}",
            CLASS_BROWSER_FALLBACK,
            "Archived delete is risky and guarded.",
        ),
        ApiSurfaceMethod("Artifacts", "list_artifacts", "GET", "/artifacts", CLASS_TUI_MVP, "Artifact list baseline."),
        ApiSurfaceMethod(
            "Artifacts",
            "get_artifact",
            "GET",
            "/artifacts/{id}",
            CLASS_TUI_ADVANCED,
            "Artifact detail for selected object.",
        ),
        ApiSurfaceMethod(
            "Artifacts",
            "extract_artifact",
            "POST",
            "/artifacts/{id}/extract",
            CLASS_BROWSER_FALLBACK,
            "Extract action is explicit and confirmation-based.",
        ),
        ApiSurfaceMethod(
            "Artifacts",
            "index_artifact",
            "POST",
            "/artifacts/{id}/rag-index",
            CLASS_BROWSER_FALLBACK,
            "RAG indexing action is explicit and confirmation-based.",
        ),
        ApiSurfaceMethod(
            "Artifacts",
            "get_artifact_rag_status",
            "GET",
            "/artifacts/{id}/rag-status",
            CLASS_TUI_ADVANCED,
            "RAG indexing status for selected artifact.",
        ),
        ApiSurfaceMethod(
            "Artifacts",
            "get_artifact_rag_preview",
            "GET",
            "/artifacts/{id}/rag-preview",
            CLASS_TUI_ADVANCED,
            "RAG preview snippet view.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "list_knowledge_collections",
            "GET",
            "/knowledge/collections",
            CLASS_TUI_MVP,
            "Knowledge collection inventory.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "list_knowledge_index_profiles",
            "GET",
            "/knowledge/index-profiles",
            CLASS_TUI_ADVANCED,
            "Index profile visibility.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "get_knowledge_collection",
            "GET",
            "/knowledge/collections/{id}",
            CLASS_TUI_ADVANCED,
            "Collection detail and indexing metadata.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "index_knowledge_collection",
            "POST",
            "/knowledge/collections/{id}/index",
            CLASS_BROWSER_FALLBACK,
            "Collection indexing is explicit and guarded.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "search_knowledge_collection",
            "POST",
            "/knowledge/collections/{id}/search",
            CLASS_TUI_ADVANCED,
            "Knowledge search with query/top_k and provenance.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "list_templates",
            "GET",
            "/templates",
            CLASS_TUI_ADVANCED,
            "Template inventory and inspection list.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "get_template_variable_registry",
            "GET",
            "/templates/variable-registry",
            CLASS_TUI_ADVANCED,
            "Template variable registry view.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "get_template_sample_contexts",
            "GET",
            "/templates/sample-contexts",
            CLASS_TUI_ADVANCED,
            "Template sample contexts for operator guidance.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "validate_template",
            "POST",
            "/templates/validate",
            CLASS_TUI_ADVANCED,
            "Template validation workflow.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "preview_template",
            "POST",
            "/templates/preview",
            CLASS_TUI_ADVANCED,
            "Template preview workflow.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "template_validation_diagnostics",
            "POST",
            "/templates/validation-diagnostics",
            CLASS_TUI_ADVANCED,
            "Template diagnostics workflow.",
        ),
        ApiSurfaceMethod(
            "Knowledge",
            "upload_artifact_strategy",
            "N/A",
            "browser://artifacts/upload",
            CLASS_BROWSER_FALLBACK,
            "Direct terminal upload deferred; browser fallback is explicit strategy.",
        ),
        ApiSurfaceMethod(
            "Config", "get_config", "GET", "/config", CLASS_TUI_MVP, "Read-only config summary with redaction."
        ),
        ApiSurfaceMethod(
            "Config", "set_config", "POST", "/config", CLASS_BROWSER_FALLBACK, "Only allowlisted keys from terminal."
        ),
        ApiSurfaceMethod("Config", "list_providers", "GET", "/providers", CLASS_TUI_MVP, "Provider inventory summary."),
        ApiSurfaceMethod(
            "Config",
            "list_provider_catalog",
            "GET",
            "/providers/catalog",
            CLASS_TUI_ADVANCED,
            "Provider catalog metadata.",
        ),
        ApiSurfaceMethod(
            "Config", "get_llm_benchmarks", "GET", "/llm/benchmarks", CLASS_TUI_MVP, "Benchmark summary table."
        ),
        ApiSurfaceMethod(
            "Config",
            "get_llm_benchmarks_config",
            "GET",
            "/llm/benchmarks/config",
            CLASS_TUI_ADVANCED,
            "Benchmark execution configuration.",
        ),
        ApiSurfaceMethod("System", "get_health", "GET", "/health", CLASS_TUI_MVP, "Core service liveness."),
        ApiSurfaceMethod(
            "System",
            "get_system_contracts",
            "GET",
            "/api/system/contracts",
            CLASS_TUI_MVP,
            "Contract and compatibility view.",
        ),
        ApiSurfaceMethod(
            "System", "list_agents", "GET", "/api/system/agents", CLASS_TUI_MVP, "Agent status inventory."
        ),
        ApiSurfaceMethod("System", "get_stats", "GET", "/api/system/stats", CLASS_TUI_MVP, "Current runtime metrics."),
        ApiSurfaceMethod(
            "System",
            "get_stats_history",
            "GET",
            "/api/system/stats/history",
            CLASS_TUI_ADVANCED,
            "Trend snapshot for metrics and optional live refresh polling.",
        ),
        ApiSurfaceMethod("Teams", "list_teams", "GET", "/teams", CLASS_TUI_ADVANCED, "Team visibility baseline."),
        ApiSurfaceMethod(
            "Teams",
            "list_blueprints",
            "GET",
            "/teams/blueprints",
            CLASS_TUI_ADVANCED,
            "Blueprint inventory for team composition review.",
        ),
        ApiSurfaceMethod(
            "Teams",
            "list_blueprint_catalog",
            "GET",
            "/teams/blueprints/catalog",
            CLASS_TUI_ADVANCED,
            "Blueprint catalog index.",
        ),
        ApiSurfaceMethod(
            "Teams",
            "get_blueprint",
            "GET",
            "/teams/blueprints/{id}",
            CLASS_TUI_ADVANCED,
            "Blueprint detail for selected blueprint.",
        ),
        ApiSurfaceMethod(
            "Teams",
            "list_team_types",
            "GET",
            "/teams/types",
            CLASS_TUI_ADVANCED,
            "Team type inventory.",
        ),
        ApiSurfaceMethod(
            "Teams",
            "list_team_roles",
            "GET",
            "/teams/roles",
            CLASS_TUI_ADVANCED,
            "Global role catalog.",
        ),
        ApiSurfaceMethod(
            "Teams",
            "list_roles_for_team_type",
            "GET",
            "/teams/types/{id}/roles",
            CLASS_TUI_ADVANCED,
            "Role subset for selected team type.",
        ),
        ApiSurfaceMethod(
            "Teams",
            "activate_team",
            "POST",
            "/teams/{id}/activate",
            CLASS_BROWSER_FALLBACK,
            "Activation remains confirmation-gated and auditable.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "get_instruction_layer_model",
            "GET",
            "/instruction-layers/model",
            CLASS_TUI_ADVANCED,
            "Layer schema and overridability metadata.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "get_instruction_layers_effective",
            "GET",
            "/instruction-layers/effective",
            CLASS_TUI_ADVANCED,
            "Effective instruction stack projection.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "list_instruction_profiles",
            "GET",
            "/instruction-profiles",
            CLASS_TUI_ADVANCED,
            "Instruction profile inventory.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "list_instruction_overlays",
            "GET",
            "/instruction-overlays",
            CLASS_TUI_ADVANCED,
            "Instruction overlay inventory.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "select_instruction_profile",
            "POST",
            "/instruction-profiles/{id}/select",
            CLASS_BROWSER_FALLBACK,
            "Selection changes require explicit confirmation.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "select_instruction_overlay",
            "POST",
            "/instruction-overlays/{id}/select",
            CLASS_BROWSER_FALLBACK,
            "Overlay selection changes are guarded.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "link_instruction_overlay",
            "POST",
            "/instruction-overlays/{id}/attach",
            CLASS_BROWSER_FALLBACK,
            "Overlay linking remains confirmation-gated.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "unlink_instruction_overlay",
            "POST",
            "/instruction-overlays/{id}/detach",
            CLASS_BROWSER_FALLBACK,
            "Overlay detaching remains confirmation-gated.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "set_goal_instruction_selection",
            "POST",
            "/goals/{id}/instruction-selection",
            CLASS_BROWSER_FALLBACK,
            "Goal-level selection writes remain explicit.",
        ),
        ApiSurfaceMethod(
            "Instruction",
            "set_task_instruction_selection",
            "POST",
            "/tasks/{id}/instruction-selection",
            CLASS_BROWSER_FALLBACK,
            "Task-level selection writes remain explicit.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "get_autopilot_status",
            "GET",
            "/tasks/autopilot/status",
            CLASS_TUI_ADVANCED,
            "Autopilot status card.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "get_auto_planner_status",
            "GET",
            "/tasks/auto-planner/status",
            CLASS_TUI_ADVANCED,
            "Auto-planner status card.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "get_triggers_status",
            "GET",
            "/triggers/status",
            CLASS_TUI_ADVANCED,
            "Trigger subsystem status.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "start_autopilot",
            "POST",
            "/tasks/autopilot/start",
            CLASS_BROWSER_FALLBACK,
            "Autopilot start is explicit and confirmation-gated.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "stop_autopilot",
            "POST",
            "/tasks/autopilot/stop",
            CLASS_BROWSER_FALLBACK,
            "Autopilot stop is explicit and confirmation-gated.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "tick_autopilot",
            "POST",
            "/tasks/autopilot/tick",
            CLASS_BROWSER_FALLBACK,
            "Manual tick is explicit and auditable.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "configure_auto_planner",
            "POST",
            "/tasks/auto-planner/configure",
            CLASS_BROWSER_FALLBACK,
            "Planner config writes remain guarded.",
        ),
        ApiSurfaceMethod(
            "Automation",
            "configure_triggers",
            "POST",
            "/triggers/configure",
            CLASS_BROWSER_FALLBACK,
            "Trigger config writes remain guarded.",
        ),
        ApiSurfaceMethod(
            "Audit",
            "get_audit_logs",
            "GET",
            "/api/system/audit-logs",
            CLASS_TUI_ADVANCED,
            "Paged audit list in terminal.",
        ),
        ApiSurfaceMethod(
            "Audit",
            "analyze_audit_logs",
            "POST",
            "/api/system/audit/analyze",
            CLASS_TUI_ADVANCED,
            "Audit pattern analysis with summary counters.",
        ),
        ApiSurfaceMethod("Repair", "list_repairs", "GET", "/repairs", CLASS_TUI_MVP, "Repair session overview."),
        ApiSurfaceMethod("Repair", "list_approvals", "GET", "/approvals", CLASS_TUI_MVP, "Approval queue visibility."),
        ApiSurfaceMethod(
            "Repair",
            "repair_execution_strategy",
            "N/A",
            "browser://repairs/{id}",
            CLASS_BROWSER_FALLBACK,
            "Repair execution/drilldown remains browser-first unless explicit backend APIs are available.",
        ),
        ApiSurfaceMethod(
            "Help",
            "open_in_browser",
            "N/A",
            "browser://deep-link",
            CLASS_BROWSER_FALLBACK,
            "Deep admin and risky flows stay browser-first.",
        ),
        ApiSurfaceMethod(
            "Help",
            "rich_rendering",
            "N/A",
            "terminal://unsupported",
            CLASS_NOT_TERMINAL,
            "Complex rich/binary rendering remains browser-only.",
        ),
    )


def build_hub_api_surface_map() -> dict[str, Any]:
    by_section = {section: [] for section in TUI_SECTION_ORDER}
    for entry in _entries():
        by_section.setdefault(entry.section, []).append(asdict(entry))
    return {
        "schema": "tui_frontend_api_surface_map_v1",
        "sections": list(TUI_SECTION_ORDER),
        "classification_scale": [
            CLASS_TUI_MVP,
            CLASS_TUI_ADVANCED,
            CLASS_BROWSER_FALLBACK,
            CLASS_NOT_TERMINAL,
        ],
        "by_section": by_section,
    }
