"""Curated Wikimedia corpus presets offered by the knowledge wiki import API."""

from __future__ import annotations

WIKI_IMPORT_PRESETS = [
    {
        "id": "wikipedia-de-multistream-latest",
        "label": "Wikipedia DE: Artikel Multistream (latest)",
        "description": "Empfohlen fuer ernsthaftes deutsches RAG: echter Wikimedia XML.BZ2 Multistream-Dump plus Index.",
        "corpus_url": "https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles-multistream.xml.bz2",
        "index_url": "https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles-multistream-index.txt.bz2",
        "source_id": "wikipedia-de-multistream-latest",
        "language": "de",
        "size_hint": "~8.1 GB dump + ~63 MB index",
        "recommended": True,
        "import_format": "mediawiki-multistream",
        "codecompass_prerender": True,
        "mobile_policy": {"network": "unknown", "charging": "unknown", "storage": "unknown"},
    },
    {
        "id": "wikipedia-de-pages-latest",
        "label": "Wikipedia DE: Artikel nicht-Multistream (latest)",
        "description": "Fallback ohne Multistream-Index; meist weniger praktisch fuer grosse lokale Verarbeitung.",
        "corpus_url": "https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2",
        "source_id": "wikipedia-de-pages-latest",
        "language": "de",
        "size_hint": "~7.8 GB",
        "recommended": False,
        "import_format": "mediawiki-xml",
        "codecompass_prerender": True,
        "mobile_policy": {"network": "unknown", "charging": "unknown", "storage": "unknown"},
    },
    {
        "id": "wikipedia-de-zim-mini-2026-04",
        "label": "Wikipedia DE: ZIM mini 2026-04 (Prototyp)",
        "description": "Kleiner Kiwix/ZIM-Prototyp-Dump. Sichtbar fuer Download-Planung; Import benoetigt noch ZIM-Parser.",
        "corpus_url": "https://dumps.wikimedia.org/kiwix/zim/wikipedia/wikipedia_de_all_mini_2026-04.zim",
        "source_id": "wikipedia-de-zim-mini-2026-04",
        "language": "de",
        "size_hint": "~3.9 GiB",
        "recommended": False,
        "import_format": "zim",
        "supported": False,
        "codecompass_prerender": False,
        "mobile_policy": {"network": "unknown", "charging": "unknown", "storage": "unknown"},
    },
    {
        "id": "wikipedia-de-zim-nopic-2026-01",
        "label": "Wikipedia DE: ZIM ohne Bilder 2026-01 (Prototyp)",
        "description": "Groesserer Kiwix/ZIM-Dump ohne Bilder. Sichtbar fuer spaetere ZIM-Unterstuetzung.",
        "corpus_url": "https://dumps.wikimedia.org/kiwix/zim/wikipedia/wikipedia_de_all_nopic_2026-01.zim",
        "source_id": "wikipedia-de-zim-nopic-2026-01",
        "language": "de",
        "size_hint": "~13.6 GiB",
        "recommended": False,
        "import_format": "zim",
        "supported": False,
        "codecompass_prerender": False,
        "mobile_policy": {"network": "unknown", "charging": "unknown", "storage": "unknown"},
    },
]
