from __future__ import annotations


DEFAULT_GENERATED_COMMENT_MARKERS = (
    "generated by",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated source",
)

DEFAULT_GENERATED_PATH_MARKERS = (
    "generated-sources",
    "generated/",
    "generated\\",
    "build/generated",
    "target/generated",
)


def detect_generated_code(
    rel_path: str,
    text: str,
    extra_comment_markers: list[str] | None = None,
) -> dict:
    lowered_path = rel_path.lower()
    lowered_text = text.lower()
    markers = list(DEFAULT_GENERATED_COMMENT_MARKERS)
    if extra_comment_markers:
        markers.extend(marker.lower() for marker in extra_comment_markers if marker.strip())

    reasons: list[str] = []

    if any(marker in lowered_path for marker in DEFAULT_GENERATED_PATH_MARKERS):
        reasons.append("generated_path")
    if any(marker in lowered_text for marker in markers):
        reasons.append("generated_comment")
    if "@generated" in lowered_text or "javax.annotation.generated" in lowered_text:
        reasons.append("generated_annotation")
    if "<auto-generated" in lowered_text or "<autogenerated" in lowered_text:
        reasons.append("generated_comment")
    if "jakarta.xml.bind.annotation" in lowered_text or "javax.xml.bind.annotation" in lowered_text:
        reasons.append("jaxb_annotation")
    if "this file was generated by lombok" in lowered_text:
        reasons.append("lombok_generated")

    unique_reasons = list(dict.fromkeys(reasons))
    return {
        "is_generated": bool(unique_reasons),
        "reasons": unique_reasons,
    }
