from __future__ import annotations

import unittest

from rag_helper.application.generated_code import detect_generated_code


class GeneratedCodeDetectionTests(unittest.TestCase):
    def test_detects_generated_comments_and_paths(self) -> None:
        info = detect_generated_code(
            "target/generated-sources/jaxb/User.java",
            "/* Generated by JAXB, do not edit */ class User {}",
        )

        self.assertTrue(info["is_generated"])
        self.assertIn("generated_path", info["reasons"])
        self.assertIn("generated_comment", info["reasons"])

    def test_detects_jaxb_annotations(self) -> None:
        info = detect_generated_code(
            "src/main/java/User.java",
            "import jakarta.xml.bind.annotation.XmlElement;\n@Generated\nclass User {}",
        )

        self.assertTrue(info["is_generated"])
        self.assertIn("jaxb_annotation", info["reasons"])
        self.assertIn("generated_annotation", info["reasons"])

    def test_honors_extra_comment_markers(self) -> None:
        info = detect_generated_code(
            "src/main/java/User.java",
            "// created by schema compiler\nclass User {}",
            extra_comment_markers=["schema compiler"],
        )

        self.assertTrue(info["is_generated"])
        self.assertIn("generated_comment", info["reasons"])


if __name__ == "__main__":
    unittest.main()
