from __future__ import annotations

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate backend coverage thresholds from coverage.xml.")
    parser.add_argument("--coverage-xml", default="coverage.xml", help="Path to coverage.xml generated by pytest-cov.")
    parser.add_argument(
        "--thresholds",
        default="devtools/coverage-thresholds.backend.json",
        help="Threshold file with global and package-specific minimum coverage percentages.",
    )
    return parser.parse_args()


def _load_thresholds(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    global_min = float(payload.get("global_min_percent", 0.0))
    package_mins = payload.get("package_min_percent") or {}
    return {"global_min_percent": global_min, "package_min_percent": dict(package_mins)}


def _pct(rate: str | float | int | None) -> float:
    try:
        return float(rate) * 100.0
    except Exception:
        return 0.0


def main() -> int:
    args = _parse_args()
    coverage_path = Path(args.coverage_xml)
    thresholds_path = Path(args.thresholds)
    if not coverage_path.exists():
        print(f"coverage file missing: {coverage_path}", file=sys.stderr)
        return 2
    if not thresholds_path.exists():
        print(f"threshold file missing: {thresholds_path}", file=sys.stderr)
        return 2

    thresholds = _load_thresholds(thresholds_path)
    root = ET.fromstring(coverage_path.read_text(encoding="utf-8"))

    errors: list[str] = []
    global_cov = _pct(root.attrib.get("line-rate"))
    global_min = float(thresholds["global_min_percent"])
    if global_cov < global_min:
        errors.append(f"global coverage {global_cov:.2f}% < required {global_min:.2f}%")

    required_packages: dict[str, float] = thresholds["package_min_percent"]
    package_rates: dict[str, float] = {}
    packages = root.findall("./packages/package")
    for pkg in packages:
        name = str(pkg.attrib.get("name") or "").strip()
        package_rates[name] = _pct(pkg.attrib.get("line-rate"))

    for package_name, package_min in required_packages.items():
        actual = package_rates.get(package_name)
        if actual is None:
            errors.append(f"required package '{package_name}' missing from coverage report")
            continue
        if actual < float(package_min):
            errors.append(f"package {package_name} coverage {actual:.2f}% < required {float(package_min):.2f}%")

    print(f"global_coverage={global_cov:.2f}% required={global_min:.2f}%")
    for package_name, package_min in required_packages.items():
        actual = package_rates.get(package_name)
        if actual is not None:
            print(f"package {package_name} coverage={actual:.2f}% required={float(package_min):.2f}%")

    if errors:
        print("coverage-threshold-check-failed")
        for item in errors:
            print(f"- {item}")
        return 1
    print("coverage-threshold-check-ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

