"""Shared transport and materialization limits for CodeCompass graph artifacts."""

MAX_CODECOMPASS_GRAPH_ARTIFACT_BYTES = 32 * 1024 * 1024
MAX_CODECOMPASS_SEMANTIC_RECORDS_PER_PARTITION = 5_000
MAX_CODECOMPASS_SEMANTIC_BYTES_PER_PARTITION = 4 * 1024 * 1024
# Raw semantic shards are deliberately kept below the published graph-index
# envelope.  The graph store adds indexes and provenance while materializing,
# so the worker must not spend the complete 32 MiB artifact budget on source
# JSONL alone.  The materializer remains the final fail-closed authority.
MAX_CODECOMPASS_SEMANTIC_TOTAL_OUTPUT_BYTES = 8 * 1024 * 1024
MAX_CODECOMPASS_SEMANTIC_PARTITIONS = 256
MAX_CODECOMPASS_SEMANTIC_EDGE_CANDIDATES = 20_000
MAX_CODECOMPASS_SEMANTIC_EDGE_CANDIDATE_BYTES = 16 * 1024 * 1024

__all__ = [
    "MAX_CODECOMPASS_GRAPH_ARTIFACT_BYTES",
    "MAX_CODECOMPASS_SEMANTIC_BYTES_PER_PARTITION",
    "MAX_CODECOMPASS_SEMANTIC_EDGE_CANDIDATES",
    "MAX_CODECOMPASS_SEMANTIC_EDGE_CANDIDATE_BYTES",
    "MAX_CODECOMPASS_SEMANTIC_PARTITIONS",
    "MAX_CODECOMPASS_SEMANTIC_RECORDS_PER_PARTITION",
    "MAX_CODECOMPASS_SEMANTIC_TOTAL_OUTPUT_BYTES",
]
