"""sync schema

Revision ID: 44bba8282fff
Revises: f5b741dcd5ca
Create Date: 2026-01-17 23:32:27.534860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44bba8282fff'
down_revision: Union[str, Sequence[str], None] = 'f5b741dcd5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_types_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['default_template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_url'], ['agents.url'], ),
    sa.ForeignKeyConstraint(['custom_template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_type_role_links',
    sa.Column('team_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['team_type_id'], ['team_types.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('team_type_id', 'role_id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('assigned_agent_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('assigned_role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_assigned_agent_url_agents', 'agents', ['assigned_agent_url'], ['url'])
        batch_op.create_foreign_key('fk_tasks_team_id_teams', 'teams', ['team_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_assigned_role_id_roles', 'roles', ['assigned_role_id'], ['id'])
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_teams_team_type_id_team_types', 'team_types', ['team_type_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('agent_names')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_names', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_teams_team_type_id_team_types', type_='foreignkey')
        batch_op.drop_column('team_type_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_tasks_assigned_role_id_roles', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_team_id_teams', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_assigned_agent_url_agents', type_='foreignkey')
        batch_op.drop_column('assigned_role_id')
        batch_op.drop_column('assigned_agent_url')
        batch_op.drop_column('team_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('title')

    op.drop_table('team_type_role_links')
    op.drop_table('team_members')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('team_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_types_name'))

    op.drop_table('team_types')
    # ### end Alembic commands ###
