#!/usr/bin/env python3
"""Generate the deterministic chat setting inventory used for track evidence."""
from pathlib import Path
from agent.services.chat_setting_definitions import _DEFAULTS, _OPTIONS
from agent.services.chat_setting_catalog import build_setting_schema
from client_surfaces.operator_tui.chat_state import _DEFAULT_SESSION_SETTINGS

schema=build_setting_schema(global_defaults=_DEFAULTS,session_defaults=_DEFAULT_SESSION_SETTINGS,options=_OPTIONS)
lines=["# Chat setting inventory","","Generated by `scripts/generate_chat_setting_matrix.py`. The runtime order is global → profile → session delta.","","| Key | Type | Global default | Profile default | Session default | Values | Scopes | Angular | Divergence |","|---|---|---|---|---|---|---|---|---|"]
for item in schema["settings"]:
    defaults=item["scope_defaults"];g=defaults.get("global");p=defaults.get("profile");s=defaults.get("session")
    divergence="yes — scope-specific by contract" if g is not None and s is not None and g!=s else "no"
    values=", ".join(map(str,item.get("allowed_values") or [])) or str(item.get("constraints") or "—")
    lines.append(f"| `{item['key']}` | {item['type']} | `{g}` | `{p}` | `{s}` | {values} | {', '.join(item['scopes'])} | shared schema control | {divergence} |")
lines += ["","## Migration decisions","","- `chat_use_rag`, `chat_rag_profile`, and `rag_top_k` are non-canonical legacy aliases. They are quarantined in `legacy_settings` / `legacy_settings_delta`; the canonical keys are `chat_architecture_analysis_mode`, `chat_retrieval_profile`, and `chat_rag_top_k`.","- Unknown legacy values are preserved in quarantine and never silently discarded.","- Materialized session `settings` remain a compatibility projection; only profile `settings` and session `settings_delta` are persisted as authored deltas.",""]
Path("docs/chat-setting-inventory.md").write_text("\n".join(lines),encoding="utf-8")
