#!/usr/bin/env python3
"""Generate the Angular fallback from the canonical Hub NodeDefinition contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

OUTPUT_PATH = REPOSITORY_ROOT / "frontend-angular/src/app/features/visual-process/vp-node-definitions.generated.ts"


def _task_kind(definition: dict[str, Any]) -> dict[str, Any]:
    runtime = dict(definition.get("runtime") or {})
    return {
        "id": definition["kind"],
        "label": definition["label"],
        "group": definition["category"],
        "dispatch_capable": bool(runtime.get("dispatch_capable")),
        "description": definition.get("purpose") or "",
        "implementation_status": runtime.get("implementation_status", "unknown"),
        "implementation_state": runtime.get("implementation_state", "unknown"),
        "backend_service": runtime.get("backend_service", ""),
        "deterministic": bool(runtime.get("deterministic")),
        "uses_llm": bool(runtime.get("uses_llm")),
        "uses_network": bool(runtime.get("uses_network")),
        "side_effects": list(runtime.get("side_effects") or []),
        "risk_level": runtime.get("risk_level", "unknown"),
        "legacy_aliases": list(runtime.get("legacy_aliases") or []),
        "requires_approval": bool(runtime.get("requires_approval")),
    }


def render() -> str:
    from agent.visual_process.node_definitions import list_node_definitions

    definitions = list_node_definitions()
    task_kinds = [_task_kind(definition) for definition in definitions]
    definitions_json = json.dumps(definitions, ensure_ascii=False, sort_keys=True, indent=2)
    task_kinds_json = json.dumps(task_kinds, ensure_ascii=False, sort_keys=True, indent=2)
    return (
        "/* AUTO-GENERATED by scripts/generate_visual_process_node_definitions.py. */\n"
        "/* Do not edit manually; run the generator and commit the deterministic result. */\n"
        "import type { NodeDefinitionContract, TaskKindInfo } from './visual-process-api.service';\n\n"
        f"export const GENERATED_VISUAL_PROCESS_NODE_DEFINITIONS = {definitions_json} as NodeDefinitionContract[];\n\n"
        f"export const GENERATED_VISUAL_PROCESS_TASK_KINDS = {task_kinds_json} as TaskKindInfo[];\n\n"
        "export const GENERATED_VISUAL_PROCESS_NODE_REGISTRY_VERSION = "
        "GENERATED_VISUAL_PROCESS_NODE_DEFINITIONS[0]?.registry_version ?? '';\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the checked-in TypeScript artifact differs from the Hub contract.",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            print(
                "visual_process_node_definition_codegen_drift: run "
                "python scripts/generate_visual_process_node_definitions.py",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
