#!/usr/bin/env python3
"""Smoke script: render a Markdown string through BrowserDocumentAdapter.

Usage:
    python scripts/operator_tui_carbonyl_smoke.py [--launch]

    --launch   Attempt to launch CarbonylRunner if the binary is available.

Exit codes:
    0  — HTML rendered successfully (Carbonyl may not be present)
    1  — Unexpected error in adapter pipeline
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure project root is on sys.path when running as a script
_PROJECT_ROOT = Path(__file__).parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

_SAMPLE_MARKDOWN = """\
# Ananta Carbonyl Browser Smoke Test

This document was generated by `operator_tui_carbonyl_smoke.py`.

## Features Tested

- Plain **Markdown** rendering
- *Italic* text
- `inline code`
- Code fences
- Mermaid diagram block (source-only fallback)

## Code Example

```python
def hello(name: str) -> str:
    return f"Hello, {name}!"
```

## Mermaid Diagram

```mermaid
graph TD
    A[Start] --> B{Decision}
    B -- yes --> C[Do thing]
    B -- no --> D[Skip thing]
    C --> E[End]
    D --> E
```

## Security Note

Local-only rendering — no remote network requests by default.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Carbonyl browser mode smoke test")
    parser.add_argument("--launch", action="store_true", help="Launch CarbonylRunner if available")
    parser.add_argument("--cols", type=int, default=120, help="Terminal columns (default: 120)")
    parser.add_argument("--rows", type=int, default=30, help="Terminal rows (default: 30)")
    args = parser.parse_args(argv)

    # --- Step 1: Capability detection ---
    print("[smoke] Step 1: Detect Carbonyl capability")
    from client_surfaces.operator_tui.visual.runtime.capability_detector import detect_carbonyl_browser
    cap = detect_carbonyl_browser()
    print(f"  carbonyl_browser available: {cap.available}")
    if not cap.available:
        print(f"  reason: {cap.unavailable_reason}")
    else:
        print(f"  binary: {cap.extra.get('binary_path', '?')}")

    # --- Step 2: Build snapshot ---
    print("[smoke] Step 2: Build CenterContentSnapshot")
    from client_surfaces.operator_tui.visual.browser.center_content_snapshot import CenterContentSnapshot
    snapshot = CenterContentSnapshot(
        content_type="mermaid_markdown",
        title="Smoke Test Document",
        source_text=_SAMPLE_MARKDOWN,
        html_text="",
        scroll_position=0,
    )
    print(f"  content_type: {snapshot.content_type}, title: {snapshot.title!r}")

    # --- Step 3: Adapter to HTML ---
    print("[smoke] Step 3: Convert snapshot to HTML via BrowserDocumentAdapter")
    from client_surfaces.operator_tui.visual.browser.browser_document_adapter import BrowserDocumentAdapter
    adapter = BrowserDocumentAdapter()
    try:
        html_doc = adapter.to_html(snapshot)
    except Exception as exc:
        print(f"[smoke] ERROR in BrowserDocumentAdapter.to_html: {exc}", file=sys.stderr)
        return 1

    line_count = html_doc.count("\n")
    print(f"  generated HTML: {len(html_doc)} bytes, ~{line_count} lines")
    print()
    print("--- HTML OUTPUT (first 80 lines) ---")
    for line in html_doc.splitlines()[:80]:
        print(line)
    if line_count > 80:
        print(f"... ({line_count - 80} more lines)")
    print("--- END HTML OUTPUT ---")
    print()

    # --- Step 4: Security policy temp file ---
    print("[smoke] Step 4: Write HTML to temp file via BrowserSecurityPolicy")
    from client_surfaces.operator_tui.visual.browser.browser_security_policy import BrowserSecurityPolicy
    policy = BrowserSecurityPolicy(temp_root=".ananta/tmp/center-browser-smoke")
    try:
        html_path = policy.create_temp_file(html_doc, suffix=".html")
        print(f"  temp file: {html_path}")
    except Exception as exc:
        print(f"[smoke] ERROR creating temp file: {exc}", file=sys.stderr)
        return 1

    # --- Step 5: Optionally launch Carbonyl ---
    if args.launch:
        print("[smoke] Step 5: Launch CarbonylRunner")
        if not cap.available:
            print("  [SKIP] Carbonyl not available — degraded mode. TUI continues normally.")
        else:
            from client_surfaces.operator_tui.visual.browser.carbonyl_runner import (
                CarbonylNotAvailableError,
                CarbonylRunner,
            )
            runner = CarbonylRunner()
            try:
                runner.start(str(html_path), cols=args.cols, rows=args.rows)
                print(f"  carbonyl started (cols={args.cols}, rows={args.rows})")
                import time
                time.sleep(0.5)
                output = runner.read_output(timeout=0.5)
                if output:
                    print(f"  read {len(output)} bytes of output from carbonyl")
                runner.stop()
                print("  carbonyl stopped cleanly")
            except CarbonylNotAvailableError as exc:
                print(f"  [DEGRADED] Carbonyl not available: {exc}")
            except Exception as exc:
                print(f"  [ERROR] CarbonylRunner: {exc}")
    else:
        print("[smoke] Step 5: --launch not set, skipping CarbonylRunner")

    # --- Cleanup ---
    try:
        policy.cleanup()
        print("[smoke] Temp files cleaned up")
    except Exception:
        pass

    print("[smoke] Done — adapter pipeline OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
