"""Language- and convention-based file-role classification."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import PurePosixPath


@dataclass(frozen=True, slots=True)
class FileRole:
    role: str
    confidence: float
    reasons: tuple[str, ...]


_TEST_PARTS = {"test", "tests", "spec", "specs", "__tests__"}
_FIXTURE_PARTS = {"fixture", "fixtures", "testdata", "samples", "snapshots"}
_DOC_PARTS = {"doc", "docs", "documentation"}
_BUILD_PARTS = {"dist", "build", "target", "coverage", ".cache", "out", "artifacts", "reports"}
_VENDOR_PARTS = {
    "vendor", "vendors", "third_party", "third-party", "node_modules",
    "venv", ".venv", "site-packages",
}
_GENERATED_MARKERS = (
    "generated", "do not edit", "autogenerated", "auto-generated", "@generated",
)


def classify_file_role(path: str, content_excerpt: str = "") -> FileRole:
    normalized = str(path or "").replace("\\", "/").strip("/")
    pure = PurePosixPath(normalized)
    parts = {part.lower() for part in pure.parts}
    name = pure.name.lower()
    stem = pure.stem.lower()
    content = str(content_excerpt or "").lower()[:2000]
    if parts & _VENDOR_PARTS:
        return FileRole("vendored", 0.99, ("conventional_vendor_directory",))
    if parts & _BUILD_PARTS:
        return FileRole("build_output", 0.96, ("conventional_build_directory",))
    if any(marker in content for marker in _GENERATED_MARKERS) or re.search(r"(?:\.generated\.|_generated\.)", name):
        return FileRole("generated", 0.96, ("generated_marker",))
    if parts & _FIXTURE_PARTS:
        return FileRole("fixture", 0.92, ("conventional_fixture_directory",))
    if parts & _TEST_PARTS or stem.startswith(("test_", "spec_")) or name.endswith((".spec.ts", ".test.ts", ".test.js", "test.java")):
        return FileRole("test", 0.95, ("language_test_convention",))
    if parts & _DOC_PARTS or pure.suffix.lower() in {".md", ".rst", ".adoc"}:
        return FileRole("documentation", 0.92, ("documentation_convention",))
    if pure.suffix.lower() in {".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".go", ".rs", ".c", ".cpp", ".cs", ".rb", ".php"}:
        return FileRole("production", 0.78, ("source_language_extension",))
    return FileRole("unknown", 0.35, ("insufficient_role_evidence",))


def language_for_path(path: str) -> str:
    suffix = PurePosixPath(str(path or "")).suffix.lower()
    return {
        ".py": "python", ".ts": "typescript", ".tsx": "typescript",
        ".js": "javascript", ".jsx": "javascript", ".java": "java",
        ".go": "go", ".rs": "rust", ".c": "c", ".cpp": "cpp",
        ".cs": "csharp", ".rb": "ruby", ".php": "php",
    }.get(suffix, "unknown")
