"""Re-export of agent.common.sgpt as agent.cli_backends.sgpt."""
from __future__ import annotations

from agent.common.sgpt import (  # noqa: F401
    SUPPORTED_CLI_BACKENDS,
    CLI_BACKEND_INSTALL_HINTS,
    CLI_BACKEND_VERIFY_COMMANDS,
    CLI_BACKEND_CAPABILITIES,
    _BACKEND_RUNTIME,
    _BACKEND_SEMAPHORES,
    _SemaphoreTicket,
    _acquire_backend_permit,
    _build_iteration_prompt,
    _choose_candidates,
    _format_block_header,
    _get_agent_config,
    _get_backend_semaphore,
    _get_runtime_default_provider,
    _get_runtime_provider_urls,
    _is_probably_local_base_url,
    _is_architecture_full_scan_context,
    _load_source_file_batches,
    _MAX_LINE_WINDOW,
    _normalize_ollama_openai_base_url,
    _normalize_openai_base_url,
    _read_research_context,
    _resolve_profile_api_key,
    _resolve_repo_root,
    _run_ananta_worker_iterative,
    _run_architecture_full_scan,
    _bounded_worker_int,
    get_cli_backend_capabilities,
    get_cli_backend_preflight,
    get_cli_backend_runtime_status,
    get_research_backend_preflight,
    normalize_backend_flags,
    parse_worker_tool_output,
    resolve_codex_runtime_config,
    resolve_opencode_runtime_config,
    run_ananta_worker_tool_loop,
    run_aider_command,
    run_codex_command,
    run_llm_cli_command,
    run_mistral_code_command,
    run_opencode_command,
    run_sgpt_command,
)
