port 0
tls-port 6379
tls-cert-file /run/sfu-redis-tls/server.crt
tls-key-file /run/sfu-redis-tls/server.key
tls-ca-cert-file /run/sfu-redis-tls/ca.crt
tls-auth-clients yes
aclfile /run/sfu-redis-tls/users.acl
databases 8
appendonly yes
appendfsync everysec
save 900 1
save 300 10
maxmemory-policy noeviction
protected-mode yes
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
loglevel notice
